-- all required files and classes
Object = require 'lib.classic'
require 'src.moveable'
require 'src.scaleable'
require 'src.lifetime'
require 'src.timer'
require 'src.variable_timer'
require 'src.player'
require 'src.projectile'
require 'src.enemy'
require 'src.collision'
require 'src.play'
require 'src.score'
require 'src.level'
require 'src.score_level'
require 'src.timed_level'