-- all required files and classes
Object = require 'lib.classic'
require 'src.mixins.lifetime'
require 'src.mixins.moveable'
require 'src.mixins.scaleable'
require 'src.timer'
require 'src.variable_timer'
require 'src.player'
require 'src.projectile'
require 'src.enemy'
require 'src.collision'
require 'src.play'
require 'src.score'
require 'src.level'
require 'src.score_level'
require 'src.timed_level'